### ISSUE TITLE
node cli for the node gods

### ISSUE THREAD

**Issue by gregglind** [mozilla/http-observatory-cli#12]
So, Python is Awesome, I hear, but I am a chauvinist who only does the new thing, and values purity over sense.  Therefore I want a client for node.

**Comment by gregglind** [comment]
maybe call it directly :) => https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/api.md

**Comment by april** [comment]
I had heard that node was dead and everybody was using Erlang these days?  Have I been misinformed?

**Comment by floatingatoll** [comment]
I looked through this issue and the open pull requests but I couldn't find
the node client you're describing. Could you please resubmit the link to it
here?

**Comment by gregglind** [comment]
There isn't one yet :)  It's a request.  I think it would be very quick to make, and I might hack on it next few days.

**Comment by gregglind** [comment]
Built, pending review of 'feel' at https://github.com/mozilla/observatory-cli

I am tempted to release it to npm :)  

Please link to this in the docs if possible :)

**Comment by gene1wood** [comment]
Link shown in docs to the node version.
