### ISSUE TITLE
User story: Test a list of hostnames passed on the command line using the output mode selected

### ISSUE THREAD

**Issue by amuntner** [mozilla/http-observatory-cli#5]
Right now I'm driving it with a shell script. I'd like add another command line param to accept a file containing a list of hostnames for bulk testing and reporting. 

In this mode, error messages should be saved until the testing has completed and output to stderr all at once prior to program termination to stderr, rather than having to back-scroll errors or redirect them to a file.

**Comment by gregglind** [comment]
amunter, would "throw if any don't meet some sort of filter" or "check all sites against a rule" be enough?
