### ISSUE TITLE
Nagios Plugin mode

### ISSUE THREAD

**Issue by taladar** [mozilla/http-observatory-cli#6]
It would be useful to be able to run the CLI with exit codes and output like a Nagios plugin.

The main points are
- all output on one line with clear OK, WARNING, CRITICAL, UNKNOWN at the start of the line
- exit codes 0 for OK, 1 for WARNING, 2 for CRITICAL, 3 for UNKNOWN

for details see https://nagios-plugins.org/doc/guidelines.html )

For this it might also be useful to be able to whitelist or suppress individual known bad tests.

This would allow use of the CLI in Nagios, Icinga and many other monitoring systems supporting this standard.

**Comment by april** [comment]
Great idea.  When I get a chance, I'll add a flag (like --nagios) that will exit according to this behavior.  I just have to figure out what 0, 1, and 2 will be, grade-wise.  :)

**Comment by gregglind** [comment]
Claim: this is solved [1] in the `node` client:

https://github.com/mozilla/observatory-cli

```
# will have a 'critical' if the score isn't at least 100

$ npm install -g observatory-cli  
observatory your.site.name --nagios 2  --min-score 100
```

[1] for some minimal level of solved.  If someone wants to own this part and fuss over the interface, _who actually deals with nagios_, I am all ears.
