### ISSUE TITLE
Why the exit code is not the score?

### ISSUE THREAD

**Issue by FGRibreau** [mozilla/http-observatory-cli#8]
Making the exit code the score would allow users to integrate http-observatory-cli into their build pipeline :)

**Comment by april** [comment]
Most build chains (like Travis CI) will error out if the exit code isn't 0.  How about being able to set a minimum score or minimum grade, and having it exit with code 1 if it doesn't meet that score?

**Comment by FGRibreau** [comment]
Yes, that's definitely something like that I had in mind! That would be perfect and natural as other tools works like that :)

**Comment by gregglind** [comment]
I did this as `--expect B+`  in the node client (https://github.com/mozilla/observatory-cli/)

**Comment by gregglind** [comment]
@FGRibreau the node client has a lot of options for CI work, if you want to look into it.  Holler there if they don't meet your needs.

**Comment by gene1wood** [comment]
Closing in favor of https://github.com/mozilla/observatory-cli/ which supports this
